### ISSUE TITLE
ایراد در گرفتن اطلاعات محصول

### ISSUE THREAD

**Issue by ibeshkar** [contoriel/react-native-cafe-bazaar#11]
با سلام
وقتی از متدهای نمونه استفاده میکنم با ایراد محصولی یافت نشد مواجه میشویم در صورتیکه محصول در کافه بازار فعال میباشد و از SKU محصول استفاده شده است.

ممنون میشم راهنمایی بفرمایید

**Comment by arashmilani** [comment]
Esmaeil Jan, Please post you code here so we can take a look on how to used the library.

**Comment by ibeshkar** [comment]
hi my friend
this is my code:
`<Button title={'CafeBazaar'} onPress={() => {

                    CafeBazaar.open()
                        .then(() => CafeBazaar.purchase('LANDA.FULL', '', 1840))
                        .then((details) => {
                            alert(JSON.stringify(details));
                            return CafeBazaar.close()
                        })
                        .catch(err => alert(JSON.stringify(err)));
                }}/>`

**Comment by sam9010** [comment]
Hi guys
I have this problem...
thanks that someone solve this error

**Comment by mdehghani65** [comment]
> با سلام
> وقتی از متدهای نمونه استفاده میکنم با ایراد محصولی یافت نشد مواجه میشویم در صورتیکه محصول در کافه بازار فعال میباشد و از SKU محصول استفاده شده است.
> 
> ممنون میشم راهنمایی بفرمایید

hi . make sure your project package name matches the one registered with cafebazaar admin panel

**Comment by sam9010** [comment]
Thank you for your Answer...
Yes, your answer is quite correct
