### ISSUE TITLE
inventory not loaded!

### ISSUE THREAD

**Issue by armindev22** [contoriel/react-native-cafe-bazaar#3]
return inventory not loaded! in consume

**Comment by arashmilani** [comment]
Hi there. Please specify in more details what is the issue. If you found a bug comment on how to reproduce it.

**Comment by armindev22** [comment]
in consume function i give an error that is inventory not loaded
this is my code 
  CafeBazaar.open()
            .then(() => CafeBazaar.consume("package"))
            .then((details) => {
                console.log(details)
                return CafeBazaar.close()
            })
            .catch(err => console.log('CafeBazaar err:', err))

**Comment by arashmilani** [comment]
You probably need to `CafeBazaar.loadOwnedItems()` before trying to consume any package.

**Comment by armindev22** [comment]
yes thats right my problem resolved . thanks

**Comment by mdehghani65** [comment]
why is this not documented anywhere? (coming from [here](https://github.com/BazamBazi/react-native-custom-billing))
