### ISSUE TITLE
app crashes on successful payment throwing Error: java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by sadeghbarout** [contoriel/react-native-cafe-bazaar#5]
Hi ! thank you for this good library.
when I click to purchase , cafe bazaar dialog will appear and if I cancel my payment , all thing is right But If I pay the price (or just write my password for free products) , app will crash with the following error:

`07-24 18:38:41.783 25177 25691 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
07-24 18:38:41.783 25177 25691 W ReactNativeJS: Error: java.lang.Boolean cannot be cast to java.lang.String
`

I tests this on 3 device but error appears on all of them. can you help me?

**Comment by sadeghbarout** [comment]
` CafeBazaar.open()
            .then(() =>
                CafeBazaar.purchase('251',payload,2)
                .then((details) => {

                    alert(details)
                    // console.log(details)
                })
                .catch(err => console.log('CafeBazaar err:', err)))
            .catch(err => console.log('CafeBazaar err:', err))`

**Comment by arashmilani** [comment]
What is the *type* and *content* of the `payload`. Use `typeof` and `console.log` to print out the content and let us know.

Side Note: Also I can see that you are nesting promises inside other promises. [Read this](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) to understand why this is an anti-pattern.

**Comment by sadeghbarout** [comment]
```
let date = new Date();
let payload = 'time:'+date.getTime();
```
typeof says type is **string**

**Comment by sadeghbarout** [comment]
I'm sorry!  checked my code again and I find out that 
`java.lang.Boolean cannot be cast to java.lang.String`
error occurs in another screen (as a warning) and may not related to your library but this library also crashes on success payment and main problem not solved!

**Comment by arashmilani** [comment]
So we don't have the error message causing the crash. Use `adb logcat` command in your terminal to inspect what is happening when the app crashes ([adb docs](https://developer.android.com/studio/command-line/adb)). 

Also you might be able to get the error causing the crash by building the app using Android Studio, then selecting the 'debug' tab at the bottom to see the console output.

**Comment by sadeghbarout** [comment]
Thanks for helping. I read and explore logcat and solve the problem.
 the problem was from a white space character in RSA token while copying.

**Comment by arashmilani** [comment]
you're welcome. I'm closing the issue.
